export const CALC_DATA_FETCH = 'CALC/DATA_FETCH';
export const SOCKET_SEND = 'SOCKET/SEND';
export const SOCKET_SEND_SUCCESS = 'SOCKET/SEND_SUCCESS';
export const SOCKET_SEND_FAIL = 'SOCKET/SEND_FAIL';